name: Deploy documentation on GitHub Pages
on: 
  push:
    branches:
      - docs
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Install and Build 
        run: |
          pip install -r requirements.txt
          cd docs
          make html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/html # The folder the action should deploy.
