name: Pytest

on: [push]

jobs:
  python-testing:
    runs-on: ubuntu-latest
    container:
      image: ss450555/python-sparx
    steps:
    - uses: actions/checkout@v3
    - name: Testing the code with pytest
      run: |
        pytest
