name: Pytest

on: [push]

jobs:
  python-linting:
    runs-on: ubuntu-latest
    container:
      image: ss450555/python-sparx
    steps:
    - name: Testing the code with pytest
      run: |
        pytest
